# Default configuration file for James' BanManagement Plugin
localDatabase:
    url: 'jdbc:mysql://localhost:3306/frostcast'
    username: 'root'
    password: ''
    bansTable: 'mb_bans'
    bansRecordTable: 'mb_ban_records'
    ipBansTable: 'mb_ip_bans'
    ipBansRecordTable: 'mb_ip_records'
    kicksTable: 'mb_kicks'
    mutesTable: 'mb_mutes'
    mutesRecordTable: 'mb_mutes_records'
    playerIpsTable: 'mb_player_ips'
# Only fill in if you are syncing bans accross servers
serverName: ''
checkForUpdates: true
logKicks: false
# Keep kicks for number of days, use 0 to never delete
keepKicks: 30

# Blacklist commands for muted players
mutedCommandBlacklist:
    - msg

# Simply give the permission bm.timelimit.mutes.X or bm.timelimit.bans.X to apply the time limits
# replace X with the group defined here, can be anything you like.
timeLimits:
    mutes:
        Moderator: 1h
    bans:
        Moderator: 1d

messages:
    ban: '[name] has been banned for [reason]'
    banKick: 'You have been banned for [reason]'
    tempBan: '[name] has been banned for [expires] for [reason] by [by]'
    tempBanKick: 'You have been temporarily banned for [reason]'
    ipBan: '&c[ip] has been banned for [reason]'
    ipBanKick: 'Your IP has been banned for [reason]'
    kicked: '[name] has been kicked by [by] for [reason]'
    kickedNo: '[name] has been kicked by [by]'
    kickReason: 'You have been kicked for [reason]'
    kickNoReason: 'You have been kicked'
    disconnectBan: 'You have been banned from this server for [reason]'
    disconnectTempBan: 'Your ban expires in [expires] Reason: [reason]'
    disconnectIpBan: 'Your IP has been banned from this server for [reason]'
    mute: '[name] has been muted for [reason] by [by]'
    muted: 'You have been permanently muted for [reason] by [by]'
    tempMute: '[name] has been muted for [reason] by [by] which expires in [expires]'
    tempMuted: 'You have been temporarily muted for [reason] by [by] which expires in [expires]'
    commandPermissionError: '&cYou do not have permission to use this command'
    banSelfError: '&cYou can''t ban yourself fool!'
    banExemptError: '&cYou do not have permission to ban this player'
    alreadyBannedError: '&c[name] is already banned'
    playerBanned: '[name] has been banned'
    multiplePlayersFoundError: '&cmultiple players found, please be more specific'
    importInProgressError: '&cAn import is already in progress'
    beginingPlayerImport: '&6Beginning banned player import'
    scanningDatabase: '&6'
    scanPlayersFound: '&6Players found: [found]'
    noPlayersImport: '&cNo players need importing, yay less work for me!'
    percentagePlayersImported: '&6[percent]% of players imported'
    playerImportComplete: '&6Player import complete!'
    beginingIpImport: '&6Beginning banned ip import'
    scanIpsFound: '&6Players found: [found]'
    noIpsImport: '&cNo IPs need importing, yay less work for me!'
    percentageIPsImported: '&6[percent]% of IPs imported'
    ipImportComplete: '&6IP import complete!'
    banInfo: '&cName: &6[name]\n&cCurrentBan: [currentBan]\n&cPrevious bans: [previousBans]'
    ipBanned: '[ip] has been banned'
    ipSelfError: '&cYou can''t ip ban yourself fool!'
    ipPlayerOfflineError: '&c[name] is offline, unable to retrieve IP'
    kickSelfError: '&cYou can''t kick yourself fool!'
    kickExemptError: '&cYou do not have permission to kick this player'
    playerKicked: '[name] has been kicked'
    playerNotOnline: '&cPlayer not found, are they online?'
    muteSelfError: '&cYou can''t mute yourself fool!'
    muteExemptError: '&cYou do not have permission to mute this player'
    alreadyMutedError: '&c[name] is already muted'
    playerMuted: '[name] has been muted'
    illegalDateError: '&cIllegal Date Format'
    playerTempBanned: '[name] has been temporarily banned'
    playerTempMuted: '[name] has been temporarily muted'
    unbanError: '&cYou can''t unban someone who isn''t banned!'
    playerUnbanned: '[name] has been unbanned'
    ipUnbanned: '[ip] has been unbanned'
    ipNotBannedError: '&c[ip] is not currently banned. You can''t unban someone who isn''t banned!'
    invalidIp: '&cInvalid IP!'
    playerUnmuted: '[name] has been unmuted'
    playerNotMutedError: '&cYou can''t unmute someone who isn''t muted!'
    updateAvailable: '&A[version] update available'
    banTimeLimitError: '&cYou cannot ban for that length of time'
    muteTimeLimitError: '&cYou cannot mute for that length of time'