# Default configuration file for James' BanManagement Plugin

# Required. If the connection info is wrong, the plugin may hang on startup and will eventually disable itself
localDatabase:
    host: 'localhost'
    port: 3306
    database: 'frostcast'
    username: 'root'
    password: ''
    bansTable: 'bm_bans'
    bansRecordTable: 'bm_ban_records'
    ipBansTable: 'bm_ip_bans'
    ipBansRecordTable: 'bm_ip_records'
    kicksTable: 'bm_kicks'
    mutesTable: 'bm_mutes'
    mutesRecordTable: 'bm_mutes_records'
    playerIpsTable: 'bm_player_ips'
    warningsTable: 'bm_warnings'
    banAppealsTable: 'bm_ban_appeals'
    pinsTable: 'bm_pins'
    staffTable: 'bm_staff'

# Enable for /banall & /unbanall commands
# Allows (un)banning across multiple servers that use the same exact externalDatabase.
# Optional
externalDatabase:
    enabled: false
    host: 'localhost'
    port: 3306
    database: 'frostcast'
    username: 'root'
    password: ''
    bansTable: 'bm_ban_all'
    unbansTable: 'bm_unban_all'
    ipBansTable: 'bm_ipban_all'
    ipUnbansTable: 'bm_ipunban_all'
    mutesTable: 'bm_mute_all'
    unmutesTable: 'bm_unmute_all'

# Enable for foreign characters
useUTF8: false

# Enable to log player IPs to allow for offline player ip banning and ip duplicate check of banned players on player join
logIPs: true

# Only fill in if you are syncing bans across servers
serverName: ''
checkForUpdates: true
logKicks: false

# Keep records for number of days, use 0 to never delete
cleanUp:
    kicks: 30
    banRecords: 0
    ipBanRecords: 0
    muteRecords: 0
    playerIPs: 30
    warnings: 0

# Blacklist commands for muted players
mutedCommandBlacklist:
    - msg
    
# Warning actions for when a player hits a certain number of warnings
warningActions:
    enabled: false
    '10': ban [name] [reason]

# Leave false, this is for Tekkit Classic servers
useSyncChat: false

# Simply give the permission bm.timelimit.mutes.X or bm.timelimit.bans.X to apply the time limits
# replace X with the group defined here, can be anything you like.
timeLimits:
    mutes:
        Moderator: 1h
    bans:
        Moderator: 1d

# If set to true, allows you to use partial player names in commands for online players
# If set to false, you must specify the entire name of the player
use-partial-names: true

# Bans the players and IP's within banned-players.txt & banned-ips.txt
# Only set this to false if you have a very stable MySQL connection
# If the database fails whilst this is false, banned players can join.
bukkit-ban: true

# Supports colours via &. Use \n for a new line.
messages:
    ban: '[name] has been banned for [reason]'
    banKick: 'You have been banned for [reason]'
    tempBan: '[name] has been banned for [expires] for [reason] by [by]'
    tempBanKick: 'You have been temporarily banned for [reason]'
    ipBan: '&c[ip] has been banned for [reason]'
    ipTempBan: '[ip] has been temporarily banned for [reason] by [by]'
    ipBanKick: 'Your IP has been banned for [reason]'
    kicked: '[name] has been kicked by [by] for [reason]'
    kickedNo: '[name] has been kicked by [by]'
    kickReason: 'You have been kicked for [reason]'
    kickNoReason: 'You have been kicked'
    disconnectBan: 'You have been banned from this server for [reason]'
    disconnectTempBan: 'Your ban expires in [expires] Reason: [reason]'
    disconnectIpBan: 'Your IP has been banned from this server for [reason]'
    disconnectTempIpBan: 'Your ban expires in [expires] Reason: [reason]'
    mute: '[name] has been muted for [reason] by [by]'
    muted: 'You have been permanently muted for [reason] by [by]'
    tempMute: '[name] has been muted for [reason] by [by] which expires in [expires]'
    tempMuted: 'You have been temporarily muted for [reason] by [by] which expires in [expires]'
    commandPermissionError: '&cYou do not have permission to use this command'
    banSelfError: '&cYou can''t ban yourself fool!'
    banExemptError: '&cYou do not have permission to ban this player'
    alreadyBannedError: '&c[name] is already banned'
    playerBanned: '[name] has been banned'
    multiplePlayersFoundError: '&cmultiple players found, please be more specific'
    importInProgressError: '&cAn import is already in progress'
    beginingPlayerImport: '&6Beginning banned player import'
    scanningDatabase: '&6'
    scanPlayersFound: '&6Players found: [found]'
    noPlayersImport: '&cNo players need importing, yay less work for me!'
    percentagePlayersImported: '&6[percent]% of players imported'
    playerImportComplete: '&6Player import complete!'
    beginingIpImport: '&6Beginning banned ip import'
    scanIpsFound: '&6Players found: [found]'
    noIpsImport: '&cNo IPs need importing, yay less work for me!'
    percentageIPsImported: '&6[percent]% of IPs imported'
    ipImportComplete: '&6IP import complete!'
    bmInfo: '&cName: &6[name]\n&cCurrent Ban: [currentBan]\n&cPrevious Bans: [previousBans]\n&cCurrent Mute: [currentMute]\n&cPrevious Mutes: [previousMutes]\n&cKicks: [kicksCount]\n&cWarnings: [warningsCount]'
    ipBanned: '[ip] has been banned'
    ipTempBanned: '[ip] has been banned temporarily'
    ipSelfError: '&cYou can''t ip ban yourself fool!'
    ipPlayerOfflineError: '&c[name] is offline, unable to retrieve IP'
    ipTempBanKick: 'You have been temporarily banned for [reason]'
    kickSelfError: '&cYou can''t kick yourself fool!'
    kickExemptError: '&cYou do not have permission to kick this player'
    playerKicked: '[name] has been kicked'
    playerNotOnline: '&cPlayer not found, are they online?'
    muteSelfError: '&cYou can''t mute yourself fool!'
    muteExemptError: '&cYou do not have permission to mute this player'
    alreadyMutedError: '&c[name] is already muted'
    playerMuted: '[name] has been muted'
    mutedBlacklistedCommand: '&cYou may not use that command whilst muted!'
    illegalDateError: '&cIllegal Date Format'
    playerTempBanned: '[name] has been temporarily banned'
    playerTempMuted: '[name] has been temporarily muted'
    unbanError: '&cYou can''t unban someone who isn''t banned!'
    playerUnbanned: '[name] has been unbanned'
    ipUnbanned: '[ip] has been unbanned'
    ipNotBannedError: '&c[ip] is not currently banned. You can''t unban someone who isn''t banned!'
    invalidIp: '&cInvalid IP!'
    invalidPlayer: '&cInvalid Player!'
    playerUnmuted: '[name] has been unmuted'
    playerNotMutedError: '&cYou can''t unmute someone who isn''t muted!'
    updateAvailable: '&A[version] update available'
    banTimeLimitError: '&cYou cannot ban for that length of time'
    muteTimeLimitError: '&cYou cannot mute for that length of time'
    warnSelfError: '&cYou can''t warn yourself fool!'
    warnExemptError: '&cYou do not have permission to warn this player'
    playerWarned: '[name] has been warned'
    warned: '&cYou have been warned by [by] for the following:\n[reason]'
    duplicateIP: '&cWarning: [player] has the same IP as the following banned players:\n&6[players]'
    consoleName: 'Console'
    configReloaded: '&a[BanManager] Config Reloaded.'
    invalidClearType: '&cInvalid clear type, available options are banrecords, muterecords, kicks and warnings.'
    playerRecordCleared: '[name] has had their [recordType] cleared'
    timeNow: 'now'
    timeYear: 'year'
    timeYears: 'years'
    timeMonth: 'month'
    timeMonths: 'months'
    timeDay: 'day'
    timeDays: 'days'
    timeHour: 'hour'
    timeHours: 'hours'
    timeMinute: 'minute'
    timeMinutes: 'minutes'
    timeSecond: 'second'
    timeSeconds: 'seconds'
