network_compression_threshold: 256
remote_ping_timeout: 5000
online_mode: false
remote_ping_cache: -1
forge_support: false
max_packets_per_second: 4096
ip_forward: true
disabled_commands:
- disabledcommandhere
max_packets_data_per_second: 33554432
player_limit: -1
reject_transfers: false
log_commands: false
connection_throttle_limit: 3
prevent_proxy_connections: false
connection_throttle: -1
log_pings: false
groups:
  admin:
  - admin
stats: 00000000-0000-0000-0000-000000000000
servers:
  paper:
    motd: Paper Backend
    address: paper:25565
    restricted: false
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
listeners:
- query_port: 25577
  motd: BanManager E2E Test Server
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: paper
  ping_passthrough: false
  priorities:
  - paper
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 100
  tab_size: 60
  force_default_server: true
enforce_secure_profile: false
server_connect_timeout: 5000
timeout: 30000
