# Scheduler intervals in seconds, recommended to leave as default values.
# Setting to 0 disables the scheduler from running.
# Only change if you know what you are doing!
scheduler:
  expiresCheck: 5
  playerBans: 5
  playerMutes: 5
  playerWarnings: 5
  ipBans: 5
  ipRangeBans: 5
  rollbacks: 30
  nameBans: 5
  externalPlayerBans: 5
  externalPlayerMutes: 5
  externalPlayerNotes: 5
  externalIpBans: 5
  saveLastChecked: 60
lastChecked:
  playerMutes: 1771692351
  expiresCheck: 1771692351
  nameBans: 1771692351
  playerBans: 1771692351
  playerWarnings: 1771692351
  externalPlayerNotes: 1771692351
  ipRangeBans: 1771692351
  externalPlayerMutes: 1771692351
  rollbacks: 1771692339
  externalPlayerBans: 1771692351
  externalIpBans: 1771692351
  ipBans: 1771692351
