# Scheduler intervals in seconds, recommended to leave as default values.
# Setting to 0 disables the scheduler from running.
# Only change if you know what you are doing!
scheduler:
  expiresCheck: 5
  playerBans: 5
  playerMutes: 5
  playerWarnings: 5
  ipBans: 5
  ipRangeBans: 5
  rollbacks: 30
  nameBans: 5
  externalPlayerBans: 5
  externalPlayerMutes: 5
  externalPlayerNotes: 5
  externalIpBans: 5
  saveLastChecked: 60
lastChecked:
  playerMutes: 0
  expiresCheck: 0
  nameBans: 0
  playerBans: 0
  playerWarnings: 0
  externalPlayerNotes: 0
  ipRangeBans: 0
  externalPlayerMutes: 0
  rollbacks: 0
  externalPlayerBans: 0
  externalIpBans: 0
  ipBans: 0
